# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Robert Christopher
description: > # this means to ignore newlines until "baseurl:"
  Technology can help us go green
baseurl: ""
url: "http://robert-christopher.github.io/"
github_username: Robert-Christopher

# Build settings
markdown: kramdown
